apiVersion: v2
name: monitoring
description: Monitoring setup for Todo App using Prometheus and Grafana
version: 0.1.0
type: application
dependencies:
  - name: kube-prometheus-stack
    version: 70.1.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
