apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-external-todo-api
  labels:
    app: {{ include "monitoring.name" . }}
    release: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalTodoApi.host | default "todo-app-api.onrender.com" }}
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-external-todo-api
  labels:
    app: {{ include "monitoring.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "monitoring.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}