apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-external-todo-api-health
  labels:
    app: {{ include "monitoring.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "monitoring.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /health
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }} 