apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-todo-app-api
  labels:
    app: {{ include "monitoring.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: todo-app-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - todo-app 