{{- if .Values.enabled }}
{{- $hasSecret := false }}
{{- range $key, $value := .Values.secretEnv }}
{{- if $value }}
{{- $hasSecret = true }}
{{- end }}
{{- end }}
{{- if $hasSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
